### PR TITLE
Fix undefined title in the example code

### PR DESCRIPTION
**Pull request by prestancedesign**

### CODE REVIEW

**Comment by YuukanOO** [comment]
Looks like the real issue is this line https://github.com/jordankaerim/inertia-node/blob/64a166ef5d29f2bc96fdb69f0f93bcb0471f2b47/src/index.js#L23 missing destructuring and thus assigning the `viewdata` key.

**Comment by jordankaerim** [comment]
Thanks for your comment. I somehow didn't notice there was a pull request
for this. Internally I'm actually already using a different package I am
working on that I will make public soon and is intended to replace this
package.

**Comment by YuukanOO** [comment]
And may I ask why another package? 😀

**Comment by jordankaerim** [comment]
Because this is actually my first public package and there are a few things
I would have done differently based on what I have learned so far. I would
also like to have version and feature parity with the official Laravel and
Rails adapters and most importantly I want the new package to have
integrated Inertia error handling which actually requires some sort of
cookie session. There might be people who prefer to set this up manually
and this package works fine in that case, but I feel like a node Inertia
package wouldn't be complete without also natively handling Inertia errors.
So I'm currently exploring ways of how to approach this and then put
everything together in a new package.

**Comment by prestancedesign** [comment]
Perfect answer to a good question which also interested me.
How will you know when the new version will be released?

So I close ths PR.
Best regards.

**Comment by jordankaerim** [comment]
I actually just finished the code of the new package today and tested it. All that is left to do is updating the docs and uploading it to NPM. So you can expect the package to be available sometime this week. I will share a link here once that's done. Thank you for your interest.

**Comment by prestancedesign** [comment]
Perfect, thanks.

**Comment by YuukanOO** [comment]
Nice! Thanks for reporting.

**Comment by prestancedesign** [comment]
> Because this is actually my first public package

And by the way, well done for your first public package! 👍

**Pull request closed without merging**
